In [23]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
df = pd.read_csv(r"C:\Users\rmstn\Advanced_Dataset\data\DieCasting_Quality_Raw_Data.csv")
df

,Process,Process.1,Process.2,Process.3,Process.4,Process.5,Process.6,Process.7,Process.8,Process.9,Process.10,Process.11,Process.12,Process.13,Process.14,Process.15,Process.16,Sensor,Sensor.1,Sensor.2,Sensor.3,Sensor.4,Sensor.5,Sensor.6,Sensor.7,Sensor.8,Sensor.9,Sensor.10,Sensor.11,Sensor.12,Sensor.13,Defects,Defects.1,Defects.2,Defects.3,Defects.4,Defects.5,Defects.6,Defects.7,Defects.8,Defects.9,Defects.10,Defects.11,Defects.12,Defects.13,Defects.14,Defects.15,Defects.16,Defects.17,Defects.18,Defects.19,Defects.20,Defects.21,Defects.22,Defects.23,Defects.24,Defects.25
0,id,Product_Type,Shot,Velocity_1,Velocity_2,Velocity_3,High_Velocity,Cylinder_Pressure,Rapid_Rise_Time,Biscuit_Thickness,Clamping_Force,Cycle_Time,Pressure_Rise_Time,Casting_Pressure,Spray_Time,Spray_1_Time,Spray_2_Time,Melting_Furnace_Temp,Air_Pressure,Air_Pressure_Min,Air_Pressure_Max,Coolant_Temp,Coolant_Temp_Min,Coolant_Temp_Max,Coolant_Pressure,Factory_Temp,Factory_Temp_Min,Factory_Temp_Max,Factory_Humidity,Factory_Humidity_Min,Factory_Humidity_Max,Short_Shot_1,Bubble_1,Exfoliation_1,Blow_Hole_1,Stain_1,Dent_1,Deformation_1,Contamination_1,Impurity_1,Crack_1,Scratch_1,Buring_Mark_1,Inclusions_1,Short_Shot_2,Bubble_2,Exfoliation_2,Blow_Hole_2,Stain_2,Dent_2,Deformation_2,Contamination_2,Impurity_2,Crack_2,Scratch_2,Buring_Mark_2,Inclusions_2
1,1,1,1,0.144,0.17,0.188,2.134,214,0.008,10,258,20.7,0.044,1037,7.8,0.7,0.8,695.0,6.3,3,9,26.0,10,50,2.71,32.9,18.0,22.0,58.4,18.0,22.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1002,1,2,0.144,0.17,0.182,2.124,217,0.008,11,257,20.7,0.044,1052,7.8,0.7,0.8,696.4,6.3,3,9,26.1,10,50,2.69,32.9,18.0,22.0,58.2,18.0,22.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2003,1,3,0.144,0.17,0.182,2.116,214,0.008,11,257,20.8,0.041,1037,7.8,0.7,0.8,696.4,6.3,3,9,26.1,10,50,2.69,32.9,18.0,22.0,58.2,18.0,22.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,3004,1,4,0.144,0.17,0.182,2.137,217,0.008,11,257,20.7,0.043,1051,7.8,0.7,0.8,696.4,6.3,3,9,26.1,10,50,2.69,32.9,18.0,22.0,58.2,18.0,22.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7531,7530659,2,659,0.15,0.166,0.21,2.492,265,0.011,17,381,36.2,0.033,595,12.1,2.0,2.0,667.4,6.7,3,9,28.1,10,50,2.62,32.3,18.0,22.0,69.4,18.0,22.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7532,7531660,2,660,0.144,0.174,0.206,2.514,264,0.011,16,381,36.2,0.041,595,12.1,2.0,2.0,667.8,7.0,3,9,28.1,10,50,2.62,32.2,18.0,22.0,69.5,18.0,22.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7533,7532660,2,660,0.144,0.174,0.206,2.514,264,0.011,16,381,36.2,0.041,595,12.1,2.0,2.0,667.8,7.0,3,9,28.1,10,50,2.62,32.2,18.0,22.0,69.5,18.0,22.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7534,7533661,2,661,0.147,0.174,0.204,2.532,265,0.012,18,382,36.2,0.036,596,12.1,2.0,2.0,668.5,6.8,3,9,28.1,10,50,2.62,32.2,18.0,22.0,69.6,18.0,22.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7535,7534661,2,661,0.147,0.174,0.204,2.532,265,0.012,18,382,36.2,0.036,596,12.1,2.0,2.0,668.5,6.8,3,9,28.1,10,50,2.62,32.2,18.0,22.0,69.6,18.0,22.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [22]:
df.duplicated().sum()

np.int64(0)

In [7]:
df

,Process,Process.1,Process.2,Process.3,Process.4,Process.5,Process.6,Process.7,Process.8,Process.9,Process.10,Process.11,Process.12,Process.13,Process.14,Process.15,Process.16,Sensor,Sensor.1,Sensor.2,Sensor.3,Sensor.4,Sensor.5,Sensor.6,Sensor.7,Sensor.8,Sensor.9,Sensor.10,Sensor.11,Sensor.12,Sensor.13,Defects,Defects.1,Defects.2,Defects.3,Defects.4,Defects.5,Defects.6,Defects.7,Defects.8,Defects.9,Defects.10,Defects.11,Defects.12,Defects.13,Defects.14,Defects.15,Defects.16,Defects.17,Defects.18,Defects.19,Defects.20,Defects.21,Defects.22,Defects.23,Defects.24,Defects.25
0,id,Product_Type,Shot,Velocity_1,Velocity_2,Velocity_3,High_Velocity,Cylinder_Pressure,Rapid_Rise_Time,Biscuit_Thickness,Clamping_Force,Cycle_Time,Pressure_Rise_Time,Casting_Pressure,Spray_Time,Spray_1_Time,Spray_2_Time,Melting_Furnace_Temp,Air_Pressure,Air_Pressure_Min,Air_Pressure_Max,Coolant_Temp,Coolant_Temp_Min,Coolant_Temp_Max,Coolant_Pressure,Factory_Temp,Factory_Temp_Min,Factory_Temp_Max,Factory_Humidity,Factory_Humidity_Min,Factory_Humidity_Max,Short_Shot_1,Bubble_1,Exfoliation_1,Blow_Hole_1,Stain_1,Dent_1,Deformation_1,Contamination_1,Impurity_1,Crack_1,Scratch_1,Buring_Mark_1,Inclusions_1,Short_Shot_2,Bubble_2,Exfoliation_2,Blow_Hole_2,Stain_2,Dent_2,Deformation_2,Contamination_2,Impurity_2,Crack_2,Scratch_2,Buring_Mark_2,Inclusions_2
1,1,1,1,0.144,0.17,0.188,2.134,214,0.008,10,258,20.7,0.044,1037,7.8,0.7,0.8,695.0,6.3,3,9,26.0,10,50,2.71,32.9,18.0,22.0,58.4,18.0,22.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1002,1,2,0.144,0.17,0.182,2.124,217,0.008,11,257,20.7,0.044,1052,7.8,0.7,0.8,696.4,6.3,3,9,26.1,10,50,2.69,32.9,18.0,22.0,58.2,18.0,22.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2003,1,3,0.144,0.17,0.182,2.116,214,0.008,11,257,20.8,0.041,1037,7.8,0.7,0.8,696.4,6.3,3,9,26.1,10,50,2.69,32.9,18.0,22.0,58.2,18.0,22.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,3004,1,4,0.144,0.17,0.182,2.137,217,0.008,11,257,20.7,0.043,1051,7.8,0.7,0.8,696.4,6.3,3,9,26.1,10,50,2.69,32.9,18.0,22.0,58.2,18.0,22.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7531,7530659,2,659,0.15,0.166,0.21,2.492,265,0.011,17,381,36.2,0.033,595,12.1,2.0,2.0,667.4,6.7,3,9,28.1,10,50,2.62,32.3,18.0,22.0,69.4,18.0,22.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7532,7531660,2,660,0.144,0.174,0.206,2.514,264,0.011,16,381,36.2,0.041,595,12.1,2.0,2.0,667.8,7.0,3,9,28.1,10,50,2.62,32.2,18.0,22.0,69.5,18.0,22.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7533,7532660,2,660,0.144,0.174,0.206,2.514,264,0.011,16,381,36.2,0.041,595,12.1,2.0,2.0,667.8,7.0,3,9,28.1,10,50,2.62,32.2,18.0,22.0,69.5,18.0,22.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7534,7533661,2,661,0.147,0.174,0.204,2.532,265,0.012,18,382,36.2,0.036,596,12.1,2.0,2.0,668.5,6.8,3,9,28.1,10,50,2.62,32.2,18.0,22.0,69.6,18.0,22.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7535,7534661,2,661,0.147,0.174,0.204,2.532,265,0.012,18,382,36.2,0.036,596,12.1,2.0,2.0,668.5,6.8,3,9,28.1,10,50,2.62,32.2,18.0,22.0,69.6,18.0,22.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [44]:
p_df = df.iloc[:, 0:17]
p_df

,Process,Process.1,Process.2,Process.3,Process.4,Process.5,Process.6,Process.7,Process.8,Process.9,Process.10,Process.11,Process.12,Process.13,Process.14,Process.15,Process.16
0,id,Product_Type,Shot,Velocity_1,Velocity_2,Velocity_3,High_Velocity,Cylinder_Pressure,Rapid_Rise_Time,Biscuit_Thickness,Clamping_Force,Cycle_Time,Pressure_Rise_Time,Casting_Pressure,Spray_Time,Spray_1_Time,Spray_2_Time
1,1,1,1,0.144,0.17,0.188,2.134,214,0.008,10,258,20.7,0.044,1037,7.8,0.7,0.8
2,1002,1,2,0.144,0.17,0.182,2.124,217,0.008,11,257,20.7,0.044,1052,7.8,0.7,0.8
3,2003,1,3,0.144,0.17,0.182,2.116,214,0.008,11,257,20.8,0.041,1037,7.8,0.7,0.8
4,3004,1,4,0.144,0.17,0.182,2.137,217,0.008,11,257,20.7,0.043,1051,7.8,0.7,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7531,7530659,2,659,0.15,0.166,0.21,2.492,265,0.011,17,381,36.2,0.033,595,12.1,2.0,2.0
7532,7531660,2,660,0.144,0.174,0.206,2.514,264,0.011,16,381,36.2,0.041,595,12.1,2.0,2.0
7533,7532660,2,660,0.144,0.174,0.206,2.514,264,0.011,16,381,36.2,0.041,595,12.1,2.0,2.0
7534,7533661,2,661,0.147,0.174,0.204,2.532,265,0.012,18,382,36.2,0.036,596,12.1,2.0,2.0
7535,7534661,2,661,0.147,0.174,0.204,2.532,265,0.012,18,382,36.2,0.036,596,12.1,2.0,2.0

In [19]:
s_df = df.iloc[:, 17:31]
s_df

,Sensor,Sensor.1,Sensor.2,Sensor.3,Sensor.4,Sensor.5,Sensor.6,Sensor.7,Sensor.8,Sensor.9,Sensor.10,Sensor.11,Sensor.12,Sensor.13
0,Melting_Furnace_Temp,Air_Pressure,Air_Pressure_Min,Air_Pressure_Max,Coolant_Temp,Coolant_Temp_Min,Coolant_Temp_Max,Coolant_Pressure,Factory_Temp,Factory_Temp_Min,Factory_Temp_Max,Factory_Humidity,Factory_Humidity_Min,Factory_Humidity_Max
1,695.0,6.3,3,9,26.0,10,50,2.71,32.9,18.0,22.0,58.4,18.0,22.0
2,696.4,6.3,3,9,26.1,10,50,2.69,32.9,18.0,22.0,58.2,18.0,22.0
3,696.4,6.3,3,9,26.1,10,50,2.69,32.9,18.0,22.0,58.2,18.0,22.0
4,696.4,6.3,3,9,26.1,10,50,2.69,32.9,18.0,22.0,58.2,18.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7531,667.4,6.7,3,9,28.1,10,50,2.62,32.3,18.0,22.0,69.4,18.0,22.0
7532,667.8,7.0,3,9,28.1,10,50,2.62,32.2,18.0,22.0,69.5,18.0,22.0
7533,667.8,7.0,3,9,28.1,10,50,2.62,32.2,18.0,22.0,69.5,18.0,22.0
7534,668.5,6.8,3,9,28.1,10,50,2.62,32.2,18.0,22.0,69.6,18.0,22.0
7535,668.5,6.8,3,9,28.1,10,50,2.62,32.2,18.0,22.0,69.6,18.0,22.0

In [25]:
d_df = df.iloc[:, 31:57]
d_df

,Defects,Defects.1,Defects.2,Defects.3,Defects.4,Defects.5,Defects.6,Defects.7,Defects.8,Defects.9,Defects.10,Defects.11,Defects.12,Defects.13,Defects.14,Defects.15,Defects.16,Defects.17,Defects.18,Defects.19,Defects.20,Defects.21,Defects.22,Defects.23,Defects.24,Defects.25
0,Short_Shot_1,Bubble_1,Exfoliation_1,Blow_Hole_1,Stain_1,Dent_1,Deformation_1,Contamination_1,Impurity_1,Crack_1,Scratch_1,Buring_Mark_1,Inclusions_1,Short_Shot_2,Bubble_2,Exfoliation_2,Blow_Hole_2,Stain_2,Dent_2,Deformation_2,Contamination_2,Impurity_2,Crack_2,Scratch_2,Buring_Mark_2,Inclusions_2
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7531,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7532,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7533,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7534,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7535,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
p_df.columns = p_df.iloc[0]
p_df = p_df.drop(p_df.index[0])
p_df.reset_index(drop=True)

In [51]:
p_df.convert_dtypes()

,id,Product_Type,Shot,Velocity_1,Velocity_2,Velocity_3,High_Velocity,Cylinder_Pressure,Rapid_Rise_Time,Biscuit_Thickness,Clamping_Force,Cycle_Time,Pressure_Rise_Time,Casting_Pressure,Spray_Time,Spray_1_Time,Spray_2_Time
1,1,1,1,0.144,0.17,0.188,2.134,214,0.008,10,258,20.7,0.044,1037,7.8,0.7,0.8
2,1002,1,2,0.144,0.17,0.182,2.124,217,0.008,11,257,20.7,0.044,1052,7.8,0.7,0.8
3,2003,1,3,0.144,0.17,0.182,2.116,214,0.008,11,257,20.8,0.041,1037,7.8,0.7,0.8
4,3004,1,4,0.144,0.17,0.182,2.137,217,0.008,11,257,20.7,0.043,1051,7.8,0.7,0.8
5,4005,1,5,0.144,0.172,0.176,2.111,217,0.008,12,257,20.7,0.042,1052,7.8,0.7,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7531,7530659,2,659,0.15,0.166,0.21,2.492,265,0.011,17,381,36.2,0.033,595,12.1,2.0,2.0
7532,7531660,2,660,0.144,0.174,0.206,2.514,264,0.011,16,381,36.2,0.041,595,12.1,2.0,2.0
7533,7532660,2,660,0.144,0.174,0.206,2.514,264,0.011,16,381,36.2,0.041,595,12.1,2.0,2.0
7534,7533661,2,661,0.147,0.174,0.204,2.532,265,0.012,18,382,36.2,0.036,596,12.1,2.0,2.0
7535,7534661,2,661,0.147,0.174,0.204,2.532,265,0.012,18,382,36.2,0.036,596,12.1,2.0,2.0

In [52]:
p_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7535 entries, 1 to 7535
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   7535 non-null   object
 1   Product_Type         7535 non-null   object
 2   Shot                 7535 non-null   object
 3   Velocity_1           7535 non-null   object
 4   Velocity_2           7535 non-null   object
 5   Velocity_3           7535 non-null   object
 6   High_Velocity        7535 non-null   object
 7   Cylinder_Pressure    7535 non-null   object
 8   Rapid_Rise_Time      7535 non-null   object
 9   Biscuit_Thickness    7535 non-null   object
 10  Clamping_Force       7535 non-null   object
 11  Cycle_Time           7535 non-null   object
 12   Pressure_Rise_Time  7535 non-null   object
 13  Casting_Pressure     7535 non-null   object
 14  Spray_Time           7535 non-null   object
 15  Spray_1_Time         7535 non-null   object
 16  Spray_2_Time         7535 non-null   object
dtypes: object(17)
memory usage: 1000.9+ KB